apiVersion: v2
name: mariadb
description: A Simple MariaDB helm chart with replication support, for practice and reference purposes.
type: application
version: 0.1.0
appVersion: "11.7.2"
maintainers:
- email: hery.chemo@gmail.com
  name: Heriberto Reyes Esparza
