apiVersion: v2
name: k8s-mariadb-chart
description: A Simple MariaDB helm chart with replication support, for practice and reference purposes.
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
- email: hery.chemo@gmail.com
  name: Heriberto Reyes Esparza
