# Default values for k8s-mariadb-chart.

# nameOverride is the chart base name to be used.
nameOverride: ""

# fullnameOverride is the chart final full name to be used.
fullnameOverride: ""

# replicaCount is the default number of replicas in the StatefulSet.
replicaCount: 3

# image defines values related to the image to be used.
image:
  # repository is the container repository name to use.
  repository: mariadb
  # pullPolicy is the pull policy for images.
  pullPolicy: Always
  # tag is the image tag to use, when empty the chart appVersion is used.
  tag: ""

# imagePullSecrets is used for pulling an image from a private repository.
imagePullSecrets: []

# datadir defines values related to database data directory.
datadir:
  # storageClass is the storage class to be used for the datadir pvc.
  storageClass: hostpath
  # storage is the requested amount of memory for the datadir pvc.
  storage: 80Mi

# serverIdOffset is used to generate final server id for mariaDB replication.
serverIdOffset: 700
# applicationDatabaseName is the name of the default auto-generated database.
applicationDatabaseName: application

# service defines values related to generated database service.
service:
  # port is the service port where the database will be exposed.
  port: 3306

# auth defines values related to secrets.
auth:
  # secretName is the existing secret name where to retrieve auth keys.
  #   if secretName is defined, it is expected to contain:
  #   * mariadb-root-password
  #   * mariadb-replication-username
  #   * mariadb-replication-password
  #   if secretName is not given, a secret with given auth keys will be created by the chart.
  secretName: ""
  # rootPassword is the password defined for db root user, only used when secretName not given.
  rootPassword: "30OCev&/#~1j"
  # replicationUserUsername is the user set for replication, only used when secretName not given.
  replicationUserUsername: "replication_user"
  # replicationUserPassword is the pass set for replication, only used when secretName not given.
  replicationUserPassword: "repliPa55."

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}
