apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "mariadb.fullname" . }}-cnf-configmap"
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  primary.cnf:  |
    [mariadb]
    log-bin
    log-basename=mariadb
    binlog-format=mixed
    server_id=${SERVER_ID}

  replica.cnf:  |
    [mariadb]
    log-basename=mariadb
    server_id=${SERVER_ID}
