apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "k8s-mariadb-chart.fullname" . }}-configmap"
  labels:
    {{- include "k8s-mariadb-chart.labels" . | nindent 4 }}
data:
  server-id-offset: {{ .Values.serverIdOffset | quote }}
  database-name: {{ .Values.applicationDatabaseName }}
  namespace: {{ .Release.Namespace }}
