
{{- if (include "mariadb.createSecret" .) }}

{{- $rootPassword := .Values.auth.rootPassword }}
{{- $replUser := .Values.auth.replicationUserUsername }}
{{- $replPass := .Values.auth.replicationUserPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "mariadb.fullname" . }}-secret"
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ print $rootPassword | b64enc | quote }}
  mariadb-replication-username: {{ print $replUser | b64enc | quote }}
  mariadb-replication-password: {{ print $replPass | b64enc | quote }}
{{- end -}}
