apiVersion: v1
kind: Service
metadata:
  name: "{{ include "k8s-mariadb-chart.fullname" . }}-service"
  labels:
    {{- include "k8s-mariadb-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "k8s-mariadb-chart.selectorLabels" . | nindent 4 }}
  ports:
  - name: "{{ include "k8s-mariadb-chart.fullname" . }}-port"
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 3306
